In [1]:
import numpy as np
ar=np.random.randint(0,100,24).reshape(6,4)

In [2]:
ar

array([[21, 40, 98, 68],
       [65, 54, 50, 27],
       [83, 78, 48, 54],
       [14, 76, 90,  9],
       [69, 14, 18, 75],
       [13, 70, 28, 68]])

In [3]:
a=np.arange(0,8,2)

In [4]:
a

array([0, 2, 4, 6])

In [5]:
a[[True,False,True,False]]

array([0, 4])

In [6]:
ar

array([[21, 40, 98, 68],
       [65, 54, 50, 27],
       [83, 78, 48, 54],
       [14, 76, 90,  9],
       [69, 14, 18, 75],
       [13, 70, 28, 68]])

In [7]:
ar[(ar>10) | (ar<20)]

array([21, 40, 98, 68, 65, 54, 50, 27, 83, 78, 48, 54, 14, 76, 90,  9, 69,
       14, 18, 75, 13, 70, 28, 68])

In [8]:
if [  1      ]:
    print('block if if')
else:
    print('block of else')

block if if


In [9]:
if 10%2:
    print('odd')
else:
    print('even')

even


In [10]:
e=[       ]

In [11]:
print(e)

[]


In [12]:
y='       '

In [13]:
y

'       '

In [14]:
ar.sort(axis=0)

In [15]:
ar

array([[13, 14, 18,  9],
       [14, 40, 28, 27],
       [21, 54, 48, 54],
       [65, 70, 50, 68],
       [69, 76, 90, 68],
       [83, 78, 98, 75]])

In [16]:
b=ar.ravel()

In [17]:
b

array([13, 14, 18,  9, 14, 40, 28, 27, 21, 54, 48, 54, 65, 70, 50, 68, 69,
       76, 90, 68, 83, 78, 98, 75])

In [18]:
c=ar.reshape(24,)

In [19]:
c

array([13, 14, 18,  9, 14, 40, 28, 27, 21, 54, 48, 54, 65, 70, 50, 68, 69,
       76, 90, 68, 83, 78, 98, 75])

In [20]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'a

In [21]:
d=ar.flatten()

In [22]:
d

array([13, 14, 18,  9, 14, 40, 28, 27, 21, 54, 48, 54, 65, 70, 50, 68, 69,
       76, 90, 68, 83, 78, 98, 75])

In [23]:
c

array([13, 14, 18,  9, 14, 40, 28, 27, 21, 54, 48, 54, 65, 70, 50, 68, 69,
       76, 90, 68, 83, 78, 98, 75])

In [24]:
c.sort()

In [25]:
c

array([ 9, 13, 14, 14, 18, 21, 27, 28, 40, 48, 50, 54, 54, 65, 68, 68, 69,
       70, 75, 76, 78, 83, 90, 98])

In [26]:
c.reshape(4,6)

array([[ 9, 13, 14, 14, 18, 21],
       [27, 28, 40, 48, 50, 54],
       [54, 65, 68, 68, 69, 70],
       [75, 76, 78, 83, 90, 98]])

In [27]:
from tqdm import tqdm

In [28]:
ar

array([[ 9, 13, 14, 14],
       [18, 21, 27, 28],
       [40, 48, 50, 54],
       [54, 65, 68, 68],
       [69, 70, 75, 76],
       [78, 83, 90, 98]])

In [42]:
ar>20

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

**False conditions---> False , None ,0 , {},(),[],''**

    vstack
    hstack
    linspace
    colsums
    rowsums
    sin
    cos
    tan
    deg2rad
    log
    matmul
    .dot
    std
    var
    quantile
    

In [43]:
s=100

In [45]:
r=bin(s)

In [46]:
r

'0b1100100'

In [47]:
b='0b101'

In [54]:
int(b,2)

5

In [55]:
m='0b0001011100101'

In [56]:
int(m,2)

741

In [57]:
w=741

In [58]:
bin(w)

'0b1011100101'

In [59]:
w

741

In [60]:
oct(w)

'0o1345'

In [62]:
int('0o1852',8)

ValueError: invalid literal for int() with base 8: '0o1852'

In [63]:
r=786786767678

In [64]:
hex(r)

'0xb73025533e'

In [65]:
int('0xa656abcd',16)

2790697933

In [ ]:
e='101'